@config_api.env

#@BASE_URL = http://localhost/projeto-qa/api/v1
@BASE_URL = http://fabiojcb.atwebpages.com/projeto-qa/api/v1

### USER #############################################

### Delete the user
DELETE {{BASE_URL}}/users/1

### Create a new user
POST {{BASE_URL}}/users
Content-Type: application/json

{
  "IDUSUARIO":"1",
  "NOMEUSUARIO": "User Test",
  "LOGINUSUARIO": "userteste@qa.com",
  "SENHAUSUARIO": "usertestqa",
  "NIVELUSUARIO": "1"
}

### Get the created user
GET {{BASE_URL}}/users

### Get the created user
GET {{BASE_URL}}/users/1

### Update the user
PUT {{BASE_URL}}/users/1
Content-Type: application/json

{
   "NIVELUSUARIO": "2"
}

### Delete the user
DELETE {{BASE_URL}}/users/1

### PRODUCT #############################################

### Delete the product
DELETE {{BASE_URL}}/products/1

### Create a new product
POST {{BASE_URL}}/products
Content-Type: application/json

   {
      "codProduto": "1",
      "nmProduto": "Celular Xiaomi rednote",
      "vlProduto": "1000.00",
      "dtProduto": "0000-00-00 00:00:00",
      "qtProduto": "100"
    }

### Get the created product
GET {{BASE_URL}}/products

### Get the created product
GET {{BASE_URL}}/products/1

### Update the product
PUT {{BASE_URL}}/products/1
Content-Type: application/json

  {
      "nmProduto": "Celular Xiaomi rednote update",
      "vlProduto": "1000.00",
      "dtProduto": "0000-00-00 00:00:00",
      "qtProduto": "100"
    }

### Delete the product
DELETE {{BASE_URL}}/products/1