@hostname = fabiojcb.atwebpages.com/api/rotas.php
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@endpoint = produtos

###
@cod_produto = 10
@nm_produto= Notebook Dell
@dt_Produto= {{$datetime iso8601}}
@vl_produto=10000.00
@qt_produto=10

DELETE http://{{hostname}}/{{endpoint}}
Content-Type: {{contentType}}

{
  "codProduto": "{{cod_produto}}"
}

###

# @name obterUsuario

GET http://{{hostname}}/{{endpoint}}
Content-Type: {{contentType}}


###

POST http://{{hostname}}/{{endpoint}}
Content-Type: application/json

{
  "codProduto": "{{cod_produto}}",
  "nmProduto": "{{nm_produto}}",
  "dtProduto": "{{dt_Produto}}",
  "vlProduto": "{{vl_produto}}",
  "qtProduto": "{{qt_produto}}"
}

###

PUT http://{{hostname}}/{{endpoint}}
Content-Type: {{contentType}}

{
  "codProduto": "{{cod_produto}}",
  "nmProduto": "{{nm_produto}}",
  "dtProduto": "{{dt_Produto}}",
  "vlProduto": "{{vl_produto}}",
  "qtProduto": "{{qt_produto}}"
}

### GET https://{{host}}/api/{{version}}comments/1 HTTP/1.1

GET http://{{hostname}}/{{endpoint}}
Content-Type: {{contentType}}

